version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senhaDoDB
    restart: 'always'