version: '3.9'
services:
  frontend:
    build: ./front-end
    ports:
      - 3000:3000
    working_dir: /app-frontend
    volumes:
      - ./front-end/src:/app-frontend/src
    depends_on:
      - backend
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: npm run dev
    volumes: 
      - ./back-end/src:/app-backend/src
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - API_PORT=3001
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB_NAME=delivery-app
      - EVAL_ALWAYS_RESTORE_DEV_DB=true
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'